# Generated by Django 5.0.6 on 2024-06-28 05:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="users_avatar",
                verbose_name="Аватар пользователя",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Укажите Ваш номер телефона",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Админ"), ("user", "Пользователь")],
                default="user",
                max_length=50,
                verbose_name="Роль Пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Ввведите имя Пользователя",
                max_length=50,
                null=True,
                verbose_name="Имя Пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Ввведите фамилию Пользователя",
                max_length=50,
                null=True,
                verbose_name="Фамилия Пользователя",
            ),
        ),
    ]
